# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=6, unique=True)),
                ('s_age', models.IntegerField(default=18)),
                ('s_gender', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
