# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181024_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=100)),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
