# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('pw', models.CharField(max_length=10)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
