# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=20, null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('option_time', models.DateField(auto_now_add=True)),
                ('comm_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Culumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culumn_name', models.CharField(max_length=20, unique=True)),
                ('culumn_alias', models.CharField(max_length=10, null=True)),
                ('culumn_father', models.CharField(max_length=10, null=True)),
                ('culumn_key', models.CharField(max_length=10, null=True)),
                ('culumn_description', models.CharField(max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'culumn',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='culm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Culumn'),
        ),
    ]
